setup:
	cd main && npm install
	cd main && npm run build
	cd signup-remote-component && npm install
	cd signup-remote-component && npm run build

run-remote:
	cd signup-remote-component && npm run preview

dev-remote:
	cd signup-remote-component && npm run dev

run-main:
	cd main && npm run preview
